export const offers = [
  {
    blob: '/illustrations/offer-blobs/Vector-1.svg',
    heading: 'Upptäck nya tillväxt möjligheter',
    text: 'Genom att utforska kundupplevelsen och konkurrenslandskapet identifierar vi ouppfyllda kundbehov och nya tillväxtmöjligheter.',
    buttonText: 'Nya tillväxtmöjligheter',
    category: 'digital',
    link: '/tjanster/digital/erbjudanden/tillvaxt',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-2.svg',
    heading: 'Förverkliga dina idéer',
    text: 'Baserat på dina idéer skapar vi koncept som visualiserar kund- och affärsvärde.',
    category: 'digital',
    link: '/tjanster/digital/erbjudanden/forverkliga-ideer',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-3.svg',
    heading: 'Validera idéer & koncept',
    text: 'Innan du investerar i en tekniklösning validerar vi dina idéer och koncept för att säkerställa att de möter verkliga kundbehov och tillför det förväntade affärsvärdet.',
    category: 'digital',
    link: '/tjanster/digital/erbjudanden/validera-ideer',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-4.svg',
    heading: 'Användningstester',
    text: 'Baserat på dina idéer skapar vi koncept som visualiserar kund- och affärsvärde.',
    category: 'digital',
    link: '/tjanster/digital/erbjudanden/anvandningstester',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-5.svg',
    heading: 'Tillgänglighetsgranskning',
    text: 'Vi erbjuder en omfattande service för tillgänglighetsgranskning i enlighet med EU:s tillgänglighetskrav.',
    category: 'digital',
    link: '/tjanster/digital/erbjudanden/tillganglighetsgranskning',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-6.svg',
    heading: 'Kickstarta innovation',
    text: 'Vi påbörjar resan mot en arbetsplats som uppmuntrar till kreativitet. Ni får verktyg och en genomförbar plan som steg för steg ökar er innovationsförmåga.',
    buttonText: 'Innovationsstrategi',
    category: 'strategi',
    link: '/tjanster/digital/erbjudanden/innovation',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-7.svg',
    heading: 'Kickstarta din AI strategi',
    text: 'Vi guidar  dig genom processen att kartlägga bästa vägen för AI i din organisation.',
    buttonText: 'AI-strategi',
    category: 'strategi',
    link: '/tjanster/strategi/erbjudanden/ai-strategi',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-8.svg',
    heading: 'Innovationstrategi Audit',
    text: 'Variant hjälper dig att förverkliga din innovationspotential snabbare.',
    buttonText: 'Strategi Audit',
    category: 'strategi',
    link: '/tjanster/strategi/erbjudanden/strategi-audit',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-9.svg',
    heading: 'Kommunikation & varumärke',
    text: 'Nå ut med rätt budskap till rätt målgrupp i rätt kanal!  Tillsammans arbetar vi fram en kommunikationsstrategi som skapar äkta engagemang, bygger förtroende och driver resultat.',
    category: 'kultur',
    link: '/tjanster/kultur/erbjudanden/strategi-audit',
  },
  {
    blob: '/illustrations/offer-blobs/Vector-10.svg',
    heading: 'Kulturell granskning',
    text: 'Vi påbörjar resan mot en arbetsplats som uppmuntrar till kreativitet. Ni får verktyg och en genomförbar plan som steg för steg ökar er innovationsförmåga.',
    category: 'kultur',
    link: '/tjanster/kultur/erbjudanden/kulturell-granskning',
  },
];
